# Generated by Django 2.1.7 on 2019-05-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonebrand',
            old_name='brand',
            new_name='brandName',
        ),
    ]
